import os
import glob
import pandas as pd
import matplotlib.pyplot as plt

def parse_results_file(filepath):
    # Parse the results txt files generated by run.py
    data = []
    with open(filepath, 'r') as f:
        content = f.read()
        if "**** Best strategy ****" in content:
            best_line = content.split("**** Best strategy ****")[-1].strip()
            if best_line.startswith("("):
                try:
                    tup = eval(best_line)
                    dataset = filepath.split('/')[-1].replace('_results.txt', '')
                    target_metric = tup[4]
                    value = tup[5]
                    data.append({
                        'dataset': dataset,
                        'target_metric': target_metric,
                        'best_score': value
                    })
                except Exception as e:
                    print(f"Failed to parse {filepath}: {e}")
    return data

def main():
    results_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'save')
    all_files = glob.glob(os.path.join(results_dir, '*_results.txt'))
    
    rows = []
    for f in all_files:
        rows.extend(parse_results_file(f))
        
    if not rows:
        print("No results found. Run experiments first.")
        return
        
    df = pd.DataFrame(rows)
    print(df)
    
    out_csv = os.path.join(results_dir, 'metrics_comparison.csv')
    df.to_csv(out_csv, index=False)
    print(f"Saved metric comparison to {out_csv}")
    
    plt.figure(figsize=(10, 6))
    
    groups = df.groupby('dataset')
    for name, group in groups:
        plt.scatter(group['target_metric'], group['best_score'], label=name, s=100)
        
    plt.title('Comparison of Best Pipeline Scores by Target Metric')
    plt.xlabel('Target Metric')
    plt.ylabel('Score (Higher is better for C-Index, Lower for raw IBS)')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.tight_layout()
    
    plot_file = os.path.join(results_dir, 'metrics_comparison.png')
    plt.savefig(plot_file)
    print(f"Saved plot to {plot_file}")

if __name__ == '__main__':
    main()
